services:
    # alpixel.slider.helper:
    #     class: Alpixel\Bundle\SliderBundle\Helper\SliderHelper
    #     arguments:
    #         - "@templating"
    #         - "@doctrine.orm.entity_manager"
    #         - "%alpixel_slider.template%"

    alpixel.customer_bridge.admin.translation:
        class: ~
        arguments:
            - ~
            - Alpixel\Bundle\SliderBundle\Entity\Slider
            - ~
        tags:
            - {name: sonata.admin, manager_type: orm, group: 'Diaporama', show_in_dashboard: false}
